version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FLASK_ENV: development
      FLASK_DEBUG: 1
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata: